################################################################################
# Judge0 Configuration File
################################################################################
# Judge0 is a robust and scalable open-source online code execution system.
# You can configure Judge0 with this configuration file.

# Redis
REDIS_HOST=judge0-redis
REDIS_PORT=6379
REDIS_PASSWORD=YourPassword123

# PostgreSQL
POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=YourPassword123

# Authentication
AUTHENTICATION_ENABLED=false
BYPASS_AUTHENTICATION_ON_GET=true

# API
RAILS_MAX_THREADS=5
INTERVAL=5
